# Generated by Django 5.1.6 on 2025-02-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
